---
title: "Read"
author: "Mingyin Wang"
date: 2024-09-18
output: github_document
---
load package
```{r}
library(tidyverse)
library(rvest)
library(httr)

```

laod table

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```


```{r}
drug_use_html |>
  html_table()
```

focus on first table    
```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() 
```


```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  first() |>
  slice(-1) 
table_marj

```

LC
```{r}
nyc_living = 
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |>
html_table(header = TRUE) |>
  first()

nyc_living
```


star wars
```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
title_vec = 
  swm_html |>
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |>
  html_text()

metascore_vec = 
  swm_html |>
  html_elements(".metacritic-score-box") |>
  html_text()
runtime_vec = 
  swm_html |>
  html_elements(".dli-title-metadata-item:nth-child(2)") |>
  html_text()

swm_df = 
  tibble(
    title = title_vec,
    score = metascore_vec,
    runtime = runtime_vec)
```


books

```{r}
book_html = read_html("https://books.toscrape.com/")

```

API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```

BRFSS data
```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content("parsed")

```
pokemon API

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") |>
  content()
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

